# Generated by Django 5.2.7 on 2025-10-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"verbose_name": "Платежи", "verbose_name_plural": "Платежи"},
        ),
    ]
