# Generated by Django 5.2.7 on 2025-10-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0003_alter_payments_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="price_id",
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="id стоимости для stripe"),
        ),
        migrations.AddField(
            model_name="payments",
            name="product_id",
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="id продукта для stripe"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Стоимость"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype", verbose_name="Продукт"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="date_payment",
            field=models.DateField(auto_now=True, verbose_name="Дата оплаты"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                max_length=10,
                verbose_name="Метод оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="object_id",
            field=models.PositiveIntegerField(verbose_name="id Продукта"),
        ),
    ]
