# Generated by Django 5.2.7 on 2025-10-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payments_price_id_payments_product_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="price_id",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="product_id",
        ),
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="id сессии на оплату для stripe"
            ),
        ),
    ]
