# Generated by Django 5.2.7 on 2025-10-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payments_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Стоимость"),
        ),
    ]
