# Generated by Django 5.2.7 on 2025-10-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payments_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="link",
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=600, null=True, verbose_name="id сессии на оплату для stripe"
            ),
        ),
    ]
