# Generated by Django 5.2.7 on 2025-10-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payments_link_alter_payments_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="status",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Статус оплаты"),
        ),
    ]
