# Generated by Django 5.2.7 on 2025-10-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите название курса", max_length=100, verbose_name="Название"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Загрузите картинку (превью)", upload_to="media/", verbose_name="Превью"
                    ),
                ),
                ("description", models.TextField(help_text="Введите описание курса", verbose_name="Описание курса")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите название урока", max_length=100, verbose_name="Название"),
                ),
                ("description", models.TextField(help_text="Введите описание урока", verbose_name="Описание урока")),
                (
                    "image",
                    models.ImageField(
                        help_text="Загрузите картинку (превью)", upload_to="media/", verbose_name="Превью"
                    ),
                ),
                (
                    "link_to_video",
                    models.CharField(
                        help_text="Введите ссылку на видео", max_length=150, verbose_name="Ссылка на видео"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Выберите курс",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson",
                        to="lms.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
