# Generated by Django 5.2.7 on 2025-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link_to_video",
            field=models.URLField(help_text="Введите ссылку на видео", max_length=150, verbose_name="Ссылка на видео"),
        ),
    ]
