# Generated by Django 5.2.7 on 2025-10-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_lesson_link_to_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку (превью)",
                null=True,
                upload_to="media/",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку (превью)",
                null=True,
                upload_to="media/",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="link_to_video",
            field=models.URLField(
                blank=True,
                help_text="Введите ссылку на видео",
                max_length=150,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
