# Generated by Django 5.2.7 on 2025-10-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
    ]
