# Generated by Django 5.2.7 on 2025-10-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_alter_subscription_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="update_date",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Дата обновления курса"),
        ),
    ]
