# Generated by Django 5.2.7 on 2025-10-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_course_update_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата последнего обновления курса"),
        ),
    ]
