# Generated by Django 5.2.7 on 2025-10-17 06:43

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_course_last_update_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="last_update_date",
            field=models.DateTimeField(
                default=django.db.models.functions.datetime.Now, verbose_name="Дата последнего обновления курса"
            ),
        ),
    ]
