# Generated by Django 5.2.7 on 2025-11-13 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_course_last_update_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="update_date",
        ),
        migrations.AlterField(
            model_name="course",
            name="last_update_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата последнего обновления курса"
            ),
        ),
    ]
