# Generated by Django 5.2.7 on 2025-10-17 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0009_alter_course_last_update_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="last_update_date",
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name="Дата последнего обновления курса"),
        ),
    ]
