# Generated by Django 5.2.7 on 2025-10-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0010_alter_course_last_update_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="update_date",
        ),
    ]
