# Generated by Django 5.2.7 on 2025-10-17 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0011_remove_course_update_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="last_update_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата последнего обновления курса"
            ),
        ),
    ]
